<map version="1.0.1">
<!--
Generated by com.igormaznitsa:idea-mindmap:intellij-2021.33.0-IntelliJ IDEA intellij-2021.33.0-IntelliJ IDEA (https://sciareto.org)
2023-04-26T13:54:58.4559572+05:30[Asia/Calcutta]
-->
 <node CREATED="1682497498455" MODIFIED="1682497498455" COLOR="#FFFFFF" BACKGROUND_COLOR="#031A31"   ID="mmlink65" TEXT="Design Patterns" >
  <edge WIDTH="thin"/>  <richcontent TYPE="NOTE"><html><head></head><body><p><pre>Solution to common recurring problems in Software Design</pre></p></body></html></richcontent>
  <node CREATED="1682497498455" MODIFIED="1682497498455" COLOR="#000000" BACKGROUND_COLOR="#B1BFCC" POSITION="right" ID="mmlink6565" TEXT="Creational" >
   <edge WIDTH="thin"/>   <richcontent TYPE="NOTE"><html><head></head><body><p><pre>How to create classes in different ways</pre></p></body></html></richcontent>
   <node CREATED="1682497498455" MODIFIED="1682497498455" COLOR="#000000" BACKGROUND_COLOR="#FDFDFD"   ID="mmlink656565" TEXT="Factory Method"  LINK="details/creational/FactoryMethod.md">
    <edge WIDTH="thin"/>   </node>
   <node CREATED="1682497498455" MODIFIED="1682497498455" COLOR="#000000" BACKGROUND_COLOR="#FDFDFD"   ID="mmlink656566" TEXT="Abstract Factory" >
    <edge WIDTH="thin"/>   </node>
   <node CREATED="1682497498455" MODIFIED="1682497498455" COLOR="#000000" BACKGROUND_COLOR="#FDFDFD"   ID="mmlink656567" TEXT="Singleton" >
    <edge WIDTH="thin"/>   </node>
   <node CREATED="1682497498455" MODIFIED="1682497498455" COLOR="#000000" BACKGROUND_COLOR="#FDFDFD"   ID="mmlink656568" TEXT="Builder" >
    <edge WIDTH="thin"/>   </node>
   <node CREATED="1682497498455" MODIFIED="1682497498455" COLOR="#000000" BACKGROUND_COLOR="#FDFDFD"   ID="mmlink656569" TEXT="Prototype" >
    <edge WIDTH="thin"/>   </node>
  </node>
  <node CREATED="1682497498455" MODIFIED="1682497498455" COLOR="#000000" BACKGROUND_COLOR="#B1BFCC" POSITION="left" ID="mmlink6566" TEXT="Behavioral" >
   <edge WIDTH="thin"/>   <richcontent TYPE="NOTE"><html><head></head><body><p><pre>How classes interact with each other</pre></p></body></html></richcontent>
   <node CREATED="1682497498455" MODIFIED="1682497498455" COLOR="#000000" BACKGROUND_COLOR="#FDFDFD"   ID="mmlink656665" TEXT="Chain of Responsibility" >
    <edge WIDTH="thin"/>   </node>
   <node CREATED="1682497498455" MODIFIED="1682497498455" COLOR="#000000" BACKGROUND_COLOR="#FDFDFD"   ID="mmlink656666" TEXT="Command" >
    <edge WIDTH="thin"/>   </node>
   <node CREATED="1682497498455" MODIFIED="1682497498455" COLOR="#000000" BACKGROUND_COLOR="#FDFDFD"   ID="mmlink656667" TEXT="Iterator" >
    <edge WIDTH="thin"/>   </node>
   <node CREATED="1682497498455" MODIFIED="1682497498455" COLOR="#000000" BACKGROUND_COLOR="#FDFDFD"   ID="mmlink656668" TEXT="Mediator" >
    <edge WIDTH="thin"/>   </node>
   <node CREATED="1682497498455" MODIFIED="1682497498455" COLOR="#000000" BACKGROUND_COLOR="#FDFDFD"   ID="mmlink656669" TEXT="Memento" >
    <edge WIDTH="thin"/>   </node>
   <node CREATED="1682497498455" MODIFIED="1682497498455" COLOR="#000000" BACKGROUND_COLOR="#FDFDFD"   ID="mmlink656670" TEXT="Observer" >
    <edge WIDTH="thin"/>   </node>
   <node CREATED="1682497498455" MODIFIED="1682497498455" COLOR="#000000" BACKGROUND_COLOR="#FDFDFD"   ID="mmlink656671" TEXT="State" >
    <edge WIDTH="thin"/>   </node>
   <node CREATED="1682497498455" MODIFIED="1682497498455" COLOR="#000000" BACKGROUND_COLOR="#FDFDFD"   ID="mmlink656672" TEXT="Strategy" >
    <edge WIDTH="thin"/>   </node>
   <node CREATED="1682497498455" MODIFIED="1682497498455" COLOR="#000000" BACKGROUND_COLOR="#FDFDFD"   ID="mmlink656673" TEXT="Template Method" >
    <edge WIDTH="thin"/>   </node>
   <node CREATED="1682497498455" MODIFIED="1682497498455" COLOR="#000000" BACKGROUND_COLOR="#FDFDFD"   ID="mmlink656674" TEXT="Visitor" >
    <edge WIDTH="thin"/>   </node>
  </node>
  <node CREATED="1682497498455" MODIFIED="1682497498455" COLOR="#000000" BACKGROUND_COLOR="#B1BFCC" POSITION="left" ID="mmlink6567" TEXT="Structural" >
   <edge WIDTH="thin"/>   <richcontent TYPE="NOTE"><html><head></head><body><p><pre>How we can group the classes</pre></p></body></html></richcontent>
   <node CREATED="1682497498455" MODIFIED="1682497498455" COLOR="#000000" BACKGROUND_COLOR="#FDFDFD"   ID="mmlink656765" TEXT="Adapter" >
    <edge WIDTH="thin"/>   </node>
   <node CREATED="1682497498455" MODIFIED="1682497498455" COLOR="#000000" BACKGROUND_COLOR="#FDFDFD"   ID="mmlink656766" TEXT="Bridge" >
    <edge WIDTH="thin"/>   </node>
   <node CREATED="1682497498455" MODIFIED="1682497498455" COLOR="#000000" BACKGROUND_COLOR="#FDFDFD"   ID="mmlink656767" TEXT="Composite" >
    <edge WIDTH="thin"/>   </node>
   <node CREATED="1682497498455" MODIFIED="1682497498455" COLOR="#000000" BACKGROUND_COLOR="#FDFDFD"   ID="mmlink656768" TEXT="Decorator" >
    <edge WIDTH="thin"/>   </node>
   <node CREATED="1682497498455" MODIFIED="1682497498455" COLOR="#000000" BACKGROUND_COLOR="#FDFDFD"   ID="mmlink656769" TEXT="Facade" >
    <edge WIDTH="thin"/>   </node>
   <node CREATED="1682497498455" MODIFIED="1682497498455" COLOR="#000000" BACKGROUND_COLOR="#FDFDFD"   ID="mmlink656770" TEXT="Flyweight" >
    <edge WIDTH="thin"/>   </node>
   <node CREATED="1682497498455" MODIFIED="1682497498455" COLOR="#000000" BACKGROUND_COLOR="#FDFDFD"   ID="mmlink656771" TEXT="Proxy" >
    <edge WIDTH="thin"/>   </node>
  </node>
 </node>
</map>